### ISSUE TITLE
[Bug] Free space amount doubled in warning

### ISSUE THREAD

**Issue by nephros** [Olf0/sfos-upgrade#73]
**SailfishOS VERSION**: Sailfish OS 4.4.0.72 (Vanha Rauma)
<br />**HARDWARE**: Gemini PDA 0.0.5.1
<br />**sfos-upgrade VERSION**: 3.9.11
<br />

#### BUG DESCRIPTION

The "not enough free space" warning gives twice the amount that df reports.
 
```
defaultuser@GeminiPDA:~ $ df -h /; df -k /; devel-su sfos-upgrade
Filesystem                Size      Used Available Use% Mounted on
rootfs                    2.3G      1.9G    430.0M  82% /
Filesystem           1K-blocks      Used Available Use% Mounted on
rootfs                 2454256   1971912    440368  82% /
Password:
Notice: Less than 1 GiB (880736 KiB) free space on the root filesystem.
Please consider to clean up or to enlarge the root filesystem, see:
https://gitlab.com/Olf0/sailfishX#33-increasing-the-root-lvm-volume-size
```

Not at all sure where the 880736 KiB come from, because executing the command for `$free_space` in sfos-upgrade gives: 
([relevant line in script](https://github.com/Olf0/sfos-upgrade/blob/devel/usr/bin/sfos-upgrade#L403))

```
defaultuser@GeminiPDA:~ $ df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -s -f 3 -d ' ' | rev
440368
defaultuser@GeminiPDA:~ $ echo $(( 440368 * 2 ))
880736
```

#### STEPS TO REPRODUCE

`df -k / && devel-su sfos-upgrade`

#### ADDITIONAL INFORMATION

It's not a busybox vs bash thing:
```
defaultuser@GeminiPDA:~ $ echo $BASH_VERSION
5.0.18(1)-release

defaultuser@GeminiPDA:~ $ busybox bash -c "df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -s -f 3 -d ' ' | rev"
440368
defaultuser@GeminiPDA:~ $ /bin/bash -c "df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -s -f 3 -d ' ' | rev"
440368
```

**Comment by nephros** [comment]
Not entirely related, but believe

    df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -s -f 3 -d ' ' | rev
440368

can be shortened to (the a little less zealous):

    df -P / | awk 'END {print $4}' # always use the last line
    # or
    df -P / | awk '/\s\/$/ {print $4}' # use a line ending in `space-slash`

**Comment by Olf0** [comment]
0. Thank you very much for this concise bug report.
1. [AWK]
    * Yes, AWK is the most capable of the classic UNIX string manipulation tools.
    * Hence it allows to express this example much more tersely than the combination of `grep`, `tr` and `cut`.
    * Still, these different approaches (and many others) are functionally equivalent.
    * While I loved the design and power of AWK when I prepared and held an IT-seminars on AWK a few times (two or three) two decades ago, I never used AWK in practice, because I intuitively design string manipulations around the much more basic UNIX tools, because I know them so much better and started using them another decade earlier.
    * Nowadays, I tend to ask myself non-technical questions WRT technical projects.  A crucial question for FLOSS-projects is, if the tools used (programming language, build env etc.) spur or hinder maintainability.  Here specifically: How many people know AWK well vs. how many people know `grep`, `tr` and `cut` well?  How easy is it to maintain the code in the long run?  Here AWK looses, because I would have to refresh my AWK knowledge, others might have to learn AWK, first.
    * Currently sfos-upgrade does use `grep`, `tr`, `cut` and `sed` heavily, but not at all (g)awk.  Starting to use AWK would introduce another "logical" dependency; though this does not really constitute a new technical dependency, because AWK may be present on SailfishOS by default since its inception, but one would have to check that for at least SFOS 1.0.0.5 (see [comment block at the start of the sfos-upgrade](https://github.com/Olf0/sfos-upgrade/blob/devel/usr/bin/sfos-upgrade#L6-L21) script).
    * IIRC `gawk` is fat, even when compared to `grep` and `sed`.  But then, nowadays people use Python for string manipulation because they perceive it as "more elegant", which is likely just another term for "methods I am accustomed to".  And the usual `cut` implementation has been incredibly slow since I can remember.
    * Because it is functionally equivalent and I see no real gain, but some drawbacks, I rather keep using `grep`, `tr`, `cut` and `sed`.  But I am sure open to any stronger / more convincing reasons than "it is nicer / more elegant this way", but currently I only see this one.
2. > not entirely sure what POSIX defines about df output, I use -P here in the assumption that the order of fields is more stable in POSIX than in df -k. This is likely to be wrong though, -P likely just switches the unit to "blocks" instead of (k)bytes.
   
   This is what I concluded too, after looking at this for a little while some years ago:
   *-P likely just switches the unit to "blocks" instead of (k)bytes.*
   
   But (maybe without being aware) you might have pointed at [the culprit](https://github.com/Olf0/sfos-upgrade/blob/devel/usr/bin/sfos-upgrade#L3), which exists ([via two indirections](https://github.com/Olf0/sfos-upgrade/blob/devel/usr/bin/sfos-upgrade#L17-L20)) due to Jolla's GPLv3 avoidance in the default packages.  BTW, is `gawk` not also affected, or does Jolla distribute a different AWK implementation?`
3. Can you please try:
   `defaultuser@GeminiPDA:~ $ df -h /; df -k /; export POSIXLY_CORRECT=1; df -h /; df -k /`

**Comment by nephros** [comment]
First things first (different device but same SFOS version):

```
nemo@PGXperiiia10:~ $  export POSIXLY_CORRECT=0; df -h /; df -k /; df -P /; export POSIXLY_CORRECT=1; df -h /; df -k /; df -P /
Filesystem                Size      Used Available Use% Mounted on
/dev/sailfish/root        4.7G      4.0G    643.9M  87% /
Filesystem           512-blocks     Used Available Use% Mounted on
/dev/sailfish/root     9948160   8494200   1318808  87% /
Filesystem           512-blocks     Used Available Capacity Mounted on
/dev/sailfish/root     9948160   8494200   1318808  87% /
Filesystem                Size      Used Available Use% Mounted on
/dev/sailfish/root        4.7G      4.0G    643.9M  87% /
Filesystem           512-blocks     Used Available Use% Mounted on
/dev/sailfish/root     9948160   8494200   1318808  87% /
Filesystem           512-blocks     Used Available Capacity Mounted on
/dev/sailfish/root     9948160   8494200   1318808  87% /
```

**Comment by nephros** [comment]
> BTW, is gawk not also affected (i.e., becoming a non-default package, as bash), or does Jolla distribute a different AWK implementation?

Yes it it affected, and like with similar (mostly GNU) tools, the solution is to ship an ancient GPLv2(+) version, in the case of gawk v3.1 from 2005 instead of the current GPL3 v5.x.

**Comment by nephros** [comment]
On the choice of tools, I agree with most of your points, and have no strong preference to either of the possible ways to do it.

And obviously even were that not so, it's your choice as principal designer, author, and maintainer of the sfos-upgrade tool :D

One argument could be that with a reduced set of tools used, the risk of one of them either respecting or not respecting POSIXLY_CORRECT, or in another way having non-portable or changing behaviour (by release) is higher.

Another would be performance (creating processes for each tool between the pipes has a cost) but given the context sfos-upgrade is used in, optimization in this direction is quite pointless.

The "proper" "modern" (well, 90s-unix-modern) would probably using perl to do everything. Pure perl  - maybe counter-intuitively - turns out surprisingly lean and performant when used as a UNIX filter. Or maybe not so surprising, as that, replacing sed, awk and friends, was its original purpose.
But perl has the same "people have to know it" problem you point out with AWK.

**Comment by Olf0** [comment]
[nephros](https://github.com/nephros) commented [1 hour ago](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336282513):
> I'll redo it later with the Gemini - I seem to remember that it has a block size of 1024 - which could be a hint where the factor 2 comes from.

The Gemini PDA does us a 1k block size, [as your output shows](https://github.com/Olf0/sfos-upgrade/issues/73#issue-1472564368):
```
df -k /
Filesystem           1K-blocks      Used Available Use% Mounted on
rootfs                 2454256   1971912    440368  82% /
```
That supposedly was with `POSIXLY_CORRECT=0` (the default, I assume, see `env | fgrep POSIXLY_CORRECT`, which usually yields nothing).

I am still quite curious what the exact output will be on the Gemini, but the [output of your Xperia 10 III](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336282513) nicely depicts, why this issue does not occur on devices with 512 byte blocks.

**Comment by Olf0** [comment]
On the  academical aspects:

> On the choice of tools, I agree with most of your points, and have no strong preference to either of the possible ways to do it.

One just have to love UNIX for that: One usually has plenty of tools to choose from to perform a task. :grin:

> And obviously even were that not so, it's your choice as principal designer, author, and maintainer of the sfos-upgrade tool :D

Well, nevertheless I always try to be open to suggestions, because they sometimes (in general) / often (from you) provide points one did not consider.  IMO suggestions shall be picked up or dismissed on technical grounds (which people still may evaluate differently), not by ignorance, stubbornness, arrogance, not reading or thinking thoroughly enough etc. 

> One argument could be that with a reduced set of tools used, the risk of one of them either respecting or not respecting POSIXLY_CORRECT, or in another way having non-portable or changing behaviour (by release) is higher.

I am considering to drop POSIXLY_CORRECT, but that may result in changes of behaviour, if Jolla substitutes one tool by a "compatible" one (e.g., due to GPLv3 licensing: just as it happened for `bash`→`busybox-ash`).  Ultimately the POSIX specifications (and before that X-Open's SUS ("Single UNIX Specification") with three releases: SUS v1 - SUS v3)) only exist to eliminate divergent behaviour by different implementations of the (by name or functionality) same tools.

> Another would be performance (creating processes for each tool between the pipes has a cost) but given the context sfos-upgrade is used in, optimization in this direction is quite pointless.

Yes `version --dup` (and also all `pkcon` sub-commands in other scripts) render performance optimisations futile.  Everything else in `sfos-upgrade` appears to be (relative to the slowness of `version --dup`/ `pkcon`) "fast enough", which sometimes surprises me a bit for a mildly complex shell script of 30 kbytes.

> The "proper" "modern" (well, 90s-unix-modern) would probably using perl to do everything. Pure perl - maybe counter-intuitively - turns out surprisingly lean and performant when used as a UNIX filter. Or maybe not so surprising, as that, replacing sed, awk and friends, was its original purpose. But perl has the same "people have to know it" problem you point out with AWK. It is also not exactly famous for being readable/maintainable.

1. No, "been there seen that": IMO Perl is programmers-hell (or -heaven, depending on the perspective)!  AFAICS Perl provides too much freedom to express functionally-equivalent (well, always a "maybe" for this point, because one usually does not really know) things differently, so one regularly ends up in (at least after a few months): "I do not fully comprehend why this Perl code works, but it works!", eagerly trying to believe the latter point, but with a permanent gut feeling of insecurity.
2. > "modern" (well, 90s-unix-modern)
   That was thirty years ago!  Back then I was happy to have a Slackware with Linux 0.99plXX running on my i386 with 8 MBytes RAM and a 1024×768×8 SuperVGA, which enabled me to try some things at home as an EDA-cluster admin of Apollo DomainOS and HP-UX workstations (which were only slightly better with their Motorola 68020 / 68030 CPUs and 16 MBytes of RAM).
   While memories usually become shinier over time, I do not want these times back, neither Perl or those desktop computers / workstations with less than a hundredth of the power (CPU, RAM, mass storage) of a recent smartphone (and less than a thousandth of a recent workstation).  Pearl is largely history and I do not remember those heydays of Perl and the CPAN-archive as really glorious.

  In contrast to that, Python provides vastly different properties (ones, which suit me much better), but unfortunately I fail to allocate the time to become more profound in Python for more than a decade.
   OTOH, as an "advanced sysadmin" I still get along quite well with shell-scripts, UNIX tools an sometimes a little C.

**Comment by nephros** [comment]
Onwards to the issue at hand, here's the output from the Gemini:

```
defaultuser@GeminiPDA:~ $ export POSIXLY_CORRECT=0; df -h /; df -k /; df -P /; export POSIXLY_CORRECT=1; df -h /; df -k /; df -P /
Filesystem                Size      Used Available Use% Mounted on
rootfs                    2.3G      1.9G    430.0M  82% /
Filesystem           512-blocks     Used Available Use% Mounted on
rootfs                 4908512   3943912    880648  82% /
Filesystem           512-blocks     Used Available Capacity Mounted on
rootfs                 4908512   3943912    880648  82% /
Filesystem                Size      Used Available Use% Mounted on
rootfs                    2.3G      1.9G    430.0M  82% /
Filesystem           512-blocks     Used Available Use% Mounted on
rootfs                 4908512   3943912    880648  82% /
Filesystem           512-blocks     Used Available Capacity Mounted on
rootfs                 4908512   3943912    880648  82% /
```

**Comment by Olf0** [comment]
What!?!

But that contradicts [yesterday's output generated with your Gemini PDA](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336293645)!

Something must have caused it to not count in 1k-blocks any longer?!?

**Comment by nephros** [comment]
Yes, I noticed, trying to reproduce what might cause this.

**Comment by Olf0** [comment]
> Maybe it's the fact that I upgraded from 4.4.0.68 to .72,  […]

I doubt that.

Does a `sfos-upgrade --verify` still complain about insufficient space on the root file-system with halved values compared to `du`?

**Comment by nephros** [comment]
Aha!! It is indeed another busybox-symlinks vs. GNU utilities one:

```
 xzcat systemupdate_4.4.0.72-from-4.4.0.68_2022-11-30t17-35-24.log.txt.xz   |grep -a coreutils
Finished transaction (status=1, runtime=627411ms)
 - busybox-symlinks-coreutils;1.33.1+git3-1.7.17.jolla;armv7hl;jolla


root@GeminiPDA: # pkcon remove busybox-symlinks-coreutils
Resolving
Querying
Testing changes
Finished                                                                        [                                       ] (0%)
The following packages have to be removed:
 busybox-symlinks-coreutils-1.33.1+git3-1.7.17.jolla.armv7hl    Busybox replacements for coreutils
Proceed with changes? [N/y] y


Removing
Removing packages
Resolving dependencies
Removing packages
Downloading packages
Removing packages
Installing packages
Finished

root@GeminiPDA: # df -k /
Filesystem         1K-blocks    Used Available Use% Mounted on
/dev/sailfish/root   2454256 1976256    436024  82% /

root@GeminiPDA: # pkcon install busybox-symlinks-coreutils
Resolving
Testing changes
Finished
Fatal error: the to be installed busybox-symlinks-coreutils-1.33.1+git3-1.7.17.jolla.armv7hl conflicts with 'gnu-coreutils' provided by the installed gnu-coreutils-8.31+git3-1.6.5.jolla.armv7hl

```

**Comment by nephros** [comment]
So, here's the GNU version:

```
# export POSIXLY_CORRECT=0; df -h /; df -k /; df -P /; export POSIXLY_CORRECT=1; df -h /; df -k /; df -P /
Filesystem          Size  Used Avail Use% Mounted on
/dev/sailfish/root  2.4G  1.9G  426M  82% /
Filesystem         1K-blocks    Used Available Use% Mounted on
/dev/sailfish/root   2454256 1976256    436024  82% /
Filesystem         512-blocks    Used Available Capacity Mounted on
/dev/sailfish/root    4908512 3952512    872048      82% /
Filesystem          Size  Used Avail Use% Mounted on
/dev/sailfish/root  2.4G  1.9G  426M  82% /
Filesystem         1K-blocks    Used Available Use% Mounted on
/dev/sailfish/root   2454256 1976256    436024  82% /
Filesystem         512-blocks    Used Available Capacity Mounted on
/dev/sailfish/root    4908512 3952512    872048      82% /
```

**Comment by nephros** [comment]
And the verification of `sfos-upgrade --verify`:

GNU:

```
 # sfos-upgrade --verify
Aborting: Less than ½ GiB (436024 KiB) free space on the root filesystem!
Before retrying, please clean up or enlarge the root filesystem, see:
https://gitlab.com/Olf0/sailfishX#33-increasing-the-root-lvm-volume-size

 # pkcon remove gnu-coreutils
[...]

# sfos-upgrade --verify
Notice: Less than 1 GiB (878992 KiB) free space on the root filesystem.
Please consider to clean up or to enlarge the root filesystem, see:
https://gitlab.com/Olf0/sailfishX#33-increasing-the-root-lvm-volume-size

Notice: Mind that sfos-upgrade is best run on a freshly rebooted device.

Notice: Do you want to ensure this SailfishOS 4.4.0.72 installation to be complete and up to date? (y/N)
                                                                  
```

**Comment by nephros** [comment]
Introduced by:

 - https://github.com/sailfishos/busybox/commit/fc7167fd39177ccb1628fb2e3280e23abaee448f
 - https://github.com/sailfishos/busybox/commit/be1115ea6176add9160980ba5a7f6eb646b6d5b6

and possibly a couple of follow-ups.

**Comment by Olf0** [comment]
[nephros](https://github.com/nephros) commented [42 minutes ago](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336363671):
> Aha!! It is indeed another busybox-symlinks vs. GNU utilities one:

Oh damn, I forgot about this one, although have seen it before.

Side note:
> ```
>  xzcat systemupdate_4.4.0.72-from-4.4.0.68_2022-11-30t17-35-24.log.txt.xz   |grep -a coreutils
> Finished transaction (status=1, runtime=627411ms)
>  - busybox-symlinks-coreutils;1.33.1+git3-1.7.17.jolla;armv7hl;jolla
> ```

Cool, I never thought about keeping the SFOS-upgrade logs permanently.  Nice to see see that `sfos-upgrade`'s extensive logging is indeed useful for some.
<br />

P.S.:
[nephros](https://github.com/nephros) commented [28 minutes ago](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336363671):
> root@GeminiPDA: # pkcon install busybox-symlinks-coreutils
> Fatal error: the to be installed busybox-symlinks-coreutils-1.33.1+git3-1.7.17.jolla.armv7hl conflicts with 'gnu-coreutils' provided by the installed gnu-coreutils-8.31+git3-1.6.5.jolla.armv7hl
> ```
<br />

Apparently that was easy to resolve via …
[nephros](https://github.com/nephros) commented [42 minutes ago](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336364315):
> # pkcon remove gnu-coreutils

… and then the `pkcon install busybox-symlinks-coreutils`?

Maybe a `pkcon --allow-reinstall install busybox-symlinks-coreutils` would have done it in one go.

**Comment by Olf0** [comment]
> ... and just for reference, here's a `df` man page I found which explains the `-k` and `-P` behaviour:
> 
> https://www.unix.com/man-page/POSIX/1posix/df/

Thank you very much for looking up the POSIX spec: As so often it is worth reading it.

Actually that is not "just for reference", AFAIU, because I never considered using `df`'s options `-k` and `-P` together; I rather perceived them (not really consciously) as mutually exclusive.
Before reading the POSIX spec for `df`, I was inclined to substitute the value from `df -k` by the value of "`df -P` * 2".
Then I was considering this to be a bug in the GNU-coreutils, because the `df` option `-k` means *"in KBytes"*!
Confusingly the `df` man-page of the GNU-coreutils states in its general section below the option descriptions: *Display values are in units of the first available SIZE from --block-size, and the DF_BLOCK_SIZE, BLOCK_SIZE and BLOCKSIZE environment variables.  Otherwise, units default to 1024 bytes (or 512 if POSIXLY_CORRECT is set).*
<sub>BTW, `env | fgrep BLOCK` yields nothing on SailfishOS 4.0.1 and Ubuntu 20.04.</sub>

All other block-size related options are not supported by busybox's `df`; I checked that some years ago, and it conmcurs with the terse output of `df --help` when using busybox's `df`.

I also believe to have understood that `-P` is only about (the stability) of the output format (plus always spelling out the block size in Bytes), which concurs with the statement from the `df` man-page of the GNU-coreutils: *-P, --portability: use the POSIX output format.*

In order to meet a really qualified decision, I would really appreciate, if you once again  test busybox's `df` implementation and the one from the GNU-coreutils package on your Gemini PDA with the following command sequence:
`df -T /; echo; df -PT /; echo; df -kT /; echo; df -kPT /`

On Ubuntu 20.04 (with GNU-coreutils' `df`) this yields:
```
Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/sda1      ext4  40971488 18654320  20203736  49% /

Filesystem     Type 1024-blocks     Used Available Capacity Mounted on
/dev/sda1      ext4    40971488 18654320  20203736      49% /

Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/sda1      ext4  40971488 18654320  20203736  49% /

Filesystem     Type 1024-blocks     Used Available Capacity Mounted on
/dev/sda1      ext4    40971488 18654320  20203736      49% /
```
<sup>Note the extra spaces in the output line(s) proper (not the header line), when using the `-P` option.</sup>

P.S.:
[nephros](https://github.com/nephros) commented [1 hour ago](https://github.com/Olf0/sfos-upgrade/issues/73#issuecomment-1336365607):
> Note that there is also one replacing `sed` one: https://github.com/sailfishos/busybox/commit/c5c7ee9d1a6954ebeeec8b1aa19f4a6acc5cb3ed

OMG (in the light of these compatibility issues), that must be in SailfishOS for a while, as this MR was "comitted on Sep 29, 2020".

**Comment by nephros** [comment]
```
defaultuser@GeminiPDA:~ $ rpm -qf /bin/df
busybox-symlinks-coreutils-1.33.1+git3-1.7.17.jolla.armv7hl
defaultuser@GeminiPDA:~ $ df -T /; echo; df -PT /; echo; df -kT /; echo; df -kPT /; echo $POSIXLY_CORRECT
Filesystem           Type       1K-blocks      Used Available Use% Mounted on
rootfs               rootfs       2454256   1972784    439496  82% /

Filesystem           Type       1024-blocks    Used Available Capacity Mounted on
rootfs               rootfs       2454256   1972784    439496  82% /

Filesystem           Type       1K-blocks      Used Available Use% Mounted on
rootfs               rootfs       2454256   1972784    439496  82% /

Filesystem           Type       1024-blocks    Used Available Capacity Mounted on
rootfs               rootfs       2454256   1972784    439496  82% /

defaultuser@GeminiPDA:~ $

```

**Comment by Olf0** [comment]
# On the `POSIXLY_CORRECT` environment variable

To become ineffective POSIXLY_CORRECT has to be unset by `export -n POSIXLY_CORRECT`!  I.e., setting it to `1`, `0`, `""` or anything else activates it.

On Ubuntu 20.04 (GNU `df`) the output then changes to:
```
Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/sda1      ext4  40971488 18654956  20203100  49% /

Filesystem     Type 1024-blocks     Used Available Capacity Mounted on
/dev/sda1      ext4    40971488 18654956  20203100      49% /

Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/sda1      ext4  40971488 18654956  20203100  49% /

Filesystem     Type 1024-blocks     Used Available Capacity Mounted on
/dev/sda1      ext4    40971488 18654956  20203100      49% /
```

On SailfishOS 4.0.1 (busybox `df`) the output then changes to:
```
Filesystem           Type       512-blocks     Used Available Use% Mounted on
/dev/sailfish/root   ext4        12041104   2940024   9017168  25% /

Filesystem           Type       512-blocks     Used Available Capacity Mounted on
/dev/sailfish/root   ext4        12041104   2940024   9017168  25% /

Filesystem           Type       512-blocks     Used Available Use% Mounted on
/dev/sailfish/root   ext4        12041104   2940024   9017168  25% /

Filesystem           Type       512-blocks     Used Available Capacity Mounted on
/dev/sailfish/root   ext4        12041104   2940024   9017168  25% /
```

Thus for me, setting or unsetting `POSIXLY_CORRECT` makes a big difference for both, GNU `df` on x86-64 and busybox `df` on armv7hl (Xperia XA2).

**Comment by nephros** [comment]
Nice analysis and another example why I have memorized the saying

     it's easier to write a portable shell than a portable shell script

I picked up fro somewhere (back when I worked with commercial unixes and me and my team tried to create common environment and app launch scripts).

How to avoid dealing with all the df variants? Maybe look to `util-linux` and `lsblk` instead.

Something like

    lsblk --fs --ascii --bytes --noheadings -o "FSSIZE,FSAVAIL,FSUSE%" /dev/disk/by-label/root

may avoid the whole situation.

**Comment by Olf0** [comment]
Absolutely agreed!

But a quick glance shows that `export POSIXLY_CORRECT=1; df` will always show the values in 512 Byte blocks.  `-P` only alters the formatting with spaces and some words in the header.

Hence it is either to fully rewrite that (and for me: study new aspects of `lsblk`) or to slightly adapt the current construct and recalculate the values KBytes by: (<512 Byte value> + 1) / 2

Thank you for enabling me to make an educated decision (but not today)!

**Comment by Olf0** [comment]
> Something like
> `lsblk --fs --ascii --bytes --noheadings -o "FSSIZE,FSAVAIL,FSUSE%" /dev/disk/by-label/root`

BTW, this is not really portable either: If a volume / partition has no label set, the path `/dev/disk/by-label/<label>` does not exist.  Luckily Jolla seems to set the label `root` for the root-volume on the devices we looked at.  Potential corner case: The Jolla 1 which uses BTRFS sub-volumes (on a single BTRFS file-system) and has no classic root-volume (if I can get mine to fully boot the GUI, again, I might look up what exists in `/dev/disk/by-label/`).

But using `lsblk` is definitely much more elegant.  But the it is a much newer tool than `df`, and as I still have to support SailfishOS 1.0.0.5 (which reappears when factory-resetting a Jolla 1), I fear that it may have changed some behaviour in the last decade (I already had such a bug report with the output of a BTRFS command).

**Comment by Olf0** [comment]
Due to re-reading POSIX's and GNU's `df` man-page many times, I finally see, that this is all "kind of" documented, but IMO not in a comprehensive way.

I also saw that `-T` is not POSIX specified, even though supported by both GNU `df and busybox `df` in the same manner (at least I have not perceived any difference in behaviour or output WRT `-T` between them),
